import {readFileSync,writeFileSync} from 'node:fs';
import {song,segments,grammar,words,practices} from './content.mjs';
for (const k of ['id','title','subtitle']) if (!song[k]) throw Error('Missing song '+k);
if (segments.length!==21) throw Error('Expected 21 unique attachment slots');
if (new Set(segments.map(x=>x[0])).size!==segments.length) throw Error('Duplicate segment IDs');
if (grammar.length<15||words.length<30||practices.length<6) throw Error('Teaching coverage too small');
const html=readFileSync(new URL('index.html',import.meta.url),'utf8');
if (!html.includes('id="segment-list"') || !html.includes('id="grammar-list"') || !html.includes('id="word-list"')) throw Error('Missing study containers');
if (!html.includes("from './content.mjs'")) throw Error('Study page must render from structured content');
if (html.includes('<section id="lyrics"') || html.includes('class="joined-lyric"')) throw Error('Do not turn this page into a lyrics mirror');
writeFileSync(new URL('index.html',import.meta.url),html);
console.log('PASS: '+segments.length+' attachment slots / '+grammar.length+' grammar / '+words.length+' words / '+practices.length+' practice items.');
