import {writeFileSync} from 'node:fs';
import {rows,grammar,words,practice,parts,title} from './content.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ruby=s=>esc(s).replace(/([\p{Script=Han}々ヶ]+)\{([^{}]+)\}/gu,'<ruby>$1<rp>（</rp><rt>$2</rt><rp>）</rp></ruby>');
const lines=rows.split('\n').map(s=>s.split('|'));
const gs=grammar.split('\n').map(s=>s.split('|'));
const ws=words.split('\n').map(s=>s.split('|'));
for(const row of lines)if(row.length!==5||!gs.some(g=>g[0]===row[2]))throw Error('Invalid lyric row');
for(const row of gs)if(row.length!==7)throw Error('Invalid grammar row');
for(const row of ws)if(row.length!==5)throw Error('Invalid word row');
const link=id=>`<a href="#g-${id}">${esc(gs.find(g=>g[0]===id)[1])}</a>`;
const stages=[['月台','名詞修飾與跨行','modifier',4],['花苞','不催促的請求','negative-ok',11],['未來','條件與自問','ba',19],['背中','受惠與非你不可','nakya',33],['歸處','主觀願望與疲憊','hoshii',35],['花束','一起向前累積','teiku',54]];
const verbs=[['焦る','五段','焦らない','焦った','焦って','焦れば','焦ろう'],['誓う','五段','誓わない','誓った','誓って','誓えば','誓おう'],['分け合う','五段','分け合わない','分け合った','分け合って','分け合えば','分け合おう'],['咲く','五段','咲かない','咲いた','咲いて','咲けば','咲こう'],['咲かせる','一段活用','咲かせない','咲かせた','咲かせて','咲かせれば','咲かせよう'],['待つ','五段','待たない','待った','待って','待てば','待とう'],['過ごす','五段','過ごさない','過ごした','過ごして','過ごせば','過ごそう'],['伝える','一段','伝えない','伝えた','伝えて','伝えれば','伝えよう'],['怯える','一段','怯えない','怯えた','怯えて','怯えれば','怯えよう'],['添える','一段','添えない','添えた','添えて','添えれば','添えよう'],['振る','五段','振らない','振った','振って','振れば','振ろう'],['増やす','五段','増やさない','増やした','増やして','増やせば','増やそう'],['踏む','五段','踏まない','踏んだ','踏んで','踏めば','踏もう'],['行く','五段・て形例外','行かない','行った','行って','行けば','行こう']];
const sentenceGroups=[
 [5,6,'［僕らは］［何も見えない未来を］［誓い合った］','主題→受詞→述語。何も見えない留在未来前面，中文重排為：我們對那尚看不清的未來，彼此許下誓言。'],
 [14,16,'［これからの展開を］［二人で］［飽きるまで］［過ごしてみるからね］＋［最低限の愛を伝えながら］','を先標對象，で說一起參與的人，まで設界線，てみる是嘗試，からね是向對方說明，ながら補充相伴的生活方式。'],
 [29,30,'［素直じゃないといけない］＋［ような気がしたよ］','內句＝必須坦率；外框＝那時似乎有這種感覺。拆解時先看內句，翻譯時要把不確定感放回來。'],
 [31,34,'［優しさに甘すぎて怯えすぎた男の背中に］［掌を添えてくれるのは］［前を歩く君じゃなきゃダメだから］','先定位背中に是添える落點；掌を是受詞；くれる表我受惠；のは提出焦點；君じゃなきゃダメ說非你不可。甘すぎて也可讀成銜接整段背景，原文未用標點鎖死修飾範圍。'],
 [37,38,'［日々の辛さと僕の体が］［だらしなく帰る場所を］［探し続けている］','先找が與を，再辨認探し＋続ける；だらしなく的修飾可有歧義，教材主讀為能放下拘束歸去的地方，不把這個解讀當唯一字典義。'],
 [40,41,'［いつかの灯り（を）思い出すとき］［大切に気づくのでしょう］','括號內を是教學補足，沒有改寫原文。とき給時間框架，に標察覺對象，のでしょう把後句留在帶說明的推想。'],
 [58,58,'［［小さく揺れる影］を踏む］幸せ','兩層修飾：先問什麼影子，再問什麼幸福。小さく在動詞揺れる之前，表示輕微搖動；最外層是幸せ。']
];
const html=`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><meta name="googlebot" content="noindex,nofollow"><meta name="description" content="ハルノヒ：58行假名與逐句拆解、29組語法、48個詞語、跨行句構與回想造句。"><title>${title}｜AIMYON 日文學習</title><link rel="stylesheet" href="../ring-ding/style.css"><link rel="stylesheet" href="style.css"><script src="../ring-ding/app.js" defer></script></head><body><a class="skip" href="#lyrics">跳到逐句教材</a><header id="top"><a href="../songs/">← 歌曲列表</a> · <a href="../learning-map/?song=harunohi#routes">本曲跨歌曲地圖</a><p class="eyebrow">AIMYON NOTEBOOK · 19TH LESSON</p><h1 lang="ja">ハルノヒ</h1><p class="lead">從看不清的未來，到願意一起累積的日常。</p><p>先讀一句，再拆用字與句型，最後換成自己的話。</p><nav aria-label="教材導覽"><a href="#lyrics">58 行拆讀</a><a href="#sentences">7 組跨行句構</a><a href="#grammar">29 組語法</a><a href="#words">48 個詞語</a><a href="#conjugation">活用對照</a><a href="#practice">16 題回想與造句</a><a href="#map">概念入口</a></nav><div class="controls" hidden><button id="reading-toggle" type="button" aria-pressed="false">隱藏假名</button><button id="translation-toggle" type="button" aria-pressed="false">隱藏逐句中文</button></div></header><main>
<section class="start"><h2>一次學一小段</h2><p><strong>入門：</strong>第 11–13 行，分清不用做、請做與等著。<strong>進階：</strong>第 29–34 行，找出真正的主體和句尾。<strong>整合：</strong>第 54–58 行，解開名詞修飾與意象。</p><p class="note">歌詞依你於 2026-09-10 貼上的 58 行文字製作，保留重複、空格、問號與兩種月台字形；不是經官方核定的歌詞轉錄。中文為教學譯解；意象與省略有歧義時會明示。假名不標音高重音。</p></section>
<section id="map"><h2>六個意象，串起文法</h2><div class="map">${stages.map(([image,desc,g,n],i)=>`<article class="map-card"><span class="number">0${i+1} · ${image}</span><h3>${desc}</h3><p>${link(g)}</p><a href="#l-${n}">回到原句 ${n} →</a></article>`).join('')}</div><p>月台建立場所，花苞帶出等待；背中讓受惠可感，歸處連起日常；花束可作「一件件珍惜之物聚在一起」的記憶聯想。這是教學路線，並非作者唯一詮釋。</p></section>
<section id="lyrics"><h2>逐句拆讀：先猜，再展開</h2><p>先讀日文與假名，嘗試找助詞和句尾，再看中文；遇到が、を、の，不急著在換行處停下。</p>${lines.map(([jp,zh,g,parse,nuance],i)=>`${parts.some(p=>p[0]===i+1)?(()=>{const p=parts.find(p=>p[0]===i+1);return `<h3 class="part-title">${p[1]}</h3><p>${p[2]}</p>`})():''}<article class="line" id="l-${i+1}"><span class="meta">原文 ${i+1} / ${lines.length}</span><h3 lang="ja">${ruby(jp)}</h3><p class="translation">${esc(zh)}</p><details><summary>用字、句構與容易誤讀的地方</summary><p><strong>拆開看：</strong>${esc(parse)}</p><p><strong>語感與辨析：</strong>${esc(nuance)}</p><div class="chips">${link(g)}<a href="#practice">回想與造句</a>${i?`<a href="#l-${i}">上一行</a>`:''}${i+1<lines.length?`<a href="#l-${i+2}">下一行</a>`:''}</div></details></article>`).join('')}</section>
<section id="sentences"><h2>7 組跨行句構：句尾決定怎麼讀</h2>${sentenceGroups.map(([a,b,structure,note],i)=>`<article class="entry"><h3>${i+1}｜第 ${a}${a!==b?'–'+b:''} 行</h3><p class="formula">${esc(structure)}</p><p>${esc(note)}</p><a href="#l-${a}">回去自己拆一次 →</a></article>`).join('')}</section>
<section id="grammar"><h2>29 組語法：看懂後，換情境使用</h2><p>以下例句為教材自編。從原句連到接續規則，再用生活句確認理解；文法級別不等於歌曲整體難度。</p>${gs.map(([id,t,formation,contrast,example,zh],i)=>`<article class="entry" id="g-${id}"><h3>${String(i+1).padStart(2,'0')}｜${esc(t)}</h3><p>${esc(formation)}</p><p class="note"><strong>辨析：</strong>${esc(contrast)}</p><div class="example"><span class="meta">自編生活例句</span><p lang="ja">${ruby(example)}</p><p>${esc(zh)}</p></div><div class="chips">${lines.flatMap((r,n)=>r[2]===id?[`<a href="#l-${n+1}">原句 ${n+1}</a>`]:[]).join('')}<a href="#practice">練習轉用 →</a></div></article>`).join('')}</section>
<section id="conjugation"><h2>活用對照：先認原形，再拆接法</h2><p>本表聚焦字形變化；讀音可回詞彙區查找。五段以最後一個音換段，一段多以去る接續；複合動詞由最後的動詞決定活用。行く的て形是例外行って。</p><div class="table-scroll" role="region" aria-label="動詞活用對照，可左右滑動" tabindex="0"><table><thead><tr>${['原形','類型','否定','過去','て形','ば條件','意向形'].map(t=>`<th scope="col">${t}</th>`).join('')}</tr></thead><tbody>${verbs.map(v=>`<tr>${v.map((x,i)=>i===0?`<th scope="row" lang="ja">${esc(x)}</th>`:`<td${i>1?' lang="ja"':''}>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="note">不要只看「る」：焦る是五段，怯える是一段；分ける是一段，但分け合う整體是五段。</p></section>
<section id="words"><h2>48 個詞語與搭配</h2><p>含 47 個原文詞語／原形與 1 個易混淆對照詞「甘える」。把搭配一起記，比只背單一中文更容易使用。</p><div class="search" hidden><label for="word-search">搜尋日文、假名、中文或詞類</label><input id="word-search" type="search" placeholder="例如：あせる、五段、未來"><button id="clear-search" type="button">清除搜尋</button><p id="word-count" role="status" aria-live="polite"></p></div><div class="vocab">${ws.map(([term,reading,kind,meaning,memory],i)=>`<article class="word" id="w-${i+1}" data-search="${esc([term,reading,kind,meaning,memory].join(' '))}"><h3 lang="ja">${/[\p{Script=Han}]/u.test(term)?`<ruby>${esc(term)}<rp>（</rp><rt>${esc(reading)}</rt><rp>）</rp></ruby>`:esc(term)}</h3><span class="meta">${esc(kind)}</span><p>${esc(meaning)}</p><p><strong>記憶與辨析：</strong>${esc(memory)}</p></article>`).join('')}</div></section>
<section id="practice"><h2>8 題回想＋8 題生活造句</h2><p>收起解說，先口頭回答或寫在自己的筆記，再展開核對。造句不只有一個答案；核對接續、主體與語氣即可。</p>${practice.map(([q,a,g],i)=>`<article class="exercise" id="q-${i+1}"><span class="meta">${i<8?'回想':'生活轉用'} ${i<8?i+1:i-7} / 8</span><h3>${esc(q)}</h3><details><summary>核對答案與理由</summary><p>${ruby(a)}</p>${link(g)}</details></article>`).join('')}<div class="note"><strong>複習安排：</strong>今天先做 1–4 題；明天不看教材重答；第 4 天換生活情境；第 7 天混合複習。這是練習建議，不是學習成效保證。可到跨歌曲地圖留下自評與回想筆記。</div></section>
<section id="connections"><h2>把這首歌接回整體學習</h2><div class="map"><article class="map-card"><h3>和〈愛の花〉一起看願望</h3><p>比較てほしい是希望動作發生，てくれる是受惠視角；誰希望、誰做、是否已做，分三步找。</p><a href="../learning-map/#te-hoshii">進入願望概念 →</a></article><article class="map-card"><h3>和〈裸の心〉比較なきゃ</h3><p>なきゃよかった是後悔；じゃなきゃダメ是否定條件＋不行。不能看到縮約就只背「必須」。</p><a href="../learning-map/#regret">進入後悔概念 →</a></article><article class="map-card"><h3>和〈スケッチ〉比較陪伴</h3><p>從てくれる找出對方的動作與自己的受惠感，再改成一個生活句。</p><a href="../learning-map/#kureru">進入受惠概念 →</a></article><article class="map-card"><h3>和〈いちについて〉一起向前</h3><p>辨別實際移動與時間方向的ていく，再試用ていこう提出共同邀請。</p><a href="../learning-map/#te-iku">進入持續改變 →</a></article></div><p><a class="primary" href="../learning-map/?song=harunohi#routes">篩選本曲概念，記錄回想進度</a></p></section>
<section id="sources"><h2>文字來源與解讀範圍</h2><p>歌詞來源：本次使用者貼文。教材保留其字形，不另補網路歌詞。作品名稱參考 <a href="https://sp.aimyong.net/news/detail/621">AIMYON 官方〈ハルノヒ〉MV 公告</a>。教學拆句、中文譯解與自編例句為本教材整理；「想い出ふかし」「僕らのことで」「水色」等處保留可能解讀，未宣稱為作者認定的唯一意思。</p></section>
<noscript><p>目前未啟用 JavaScript；全部歌詞、假名、解說與答案仍可閱讀，搜尋及遮罩功能需啟用 JavaScript。</p></noscript></main><footer><a href="../songs/">回歌曲列表</a> · <a href="#top">回頁首</a><p>不必一次背完。一句能辨認，一句能解釋，再一句能自己說。</p></footer></body></html>`;
writeFileSync(new URL('index.html',import.meta.url),html);
console.log(`Built ${lines.length} lines / ${gs.length} grammar / ${ws.length} words / ${practice.length} practices.`);
