import {readFileSync,writeFileSync} from 'node:fs';
import {source,groups,grammar,words,stages,practice} from './content.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const plain=s=>s.replace(/\[[^\]]+\]/g,'');
const kana=s=>s.replace(/[\p{Script=Han}々]+\[([^\]]+)\]/gu,'$1');
const ruby=s=>esc(s).replace(/([\p{Script=Han}々]+)\[([^\]]+)\]/gu,'<ruby>$1<rp>（</rp><rt>$2</rt><rp>）</rp></ruby>');
const compact=s=>plain(s).replace(/\s/g,'');
const link=(url,text)=>`<a href="${url}">${text}</a>`;
const para=n=>link('#l-'+n,`第 ${n} 段`);
const gl=id=>{const g=grammar.find(g=>g[0]===id);if(!g)throw Error(id);return link('#g-'+id,g[1]);};
if(source.length!==8||groups.length!==source.length)throw Error('Source paragraphs');
groups.forEach((g,i)=>{if(compact(g.map(p=>p[0]).join(''))!==compact(source[i]))throw Error('Source mismatch '+i);for(const p of g){if(/[\p{Script=Han}々]/u.test(p[0].replace(/[\p{Script=Han}々]+\[[^\]]+\]/gu,'')))throw Error('Missing ruby: '+p[0]);p[3].forEach(gl);}});
const count=groups.flat().length;
const map=stages.map(([id,title,ns,path,prompt],i)=>`<article class="map-card" id="m-${id}"><span class="number">0${i+1}</span><h3>${title}</h3><p>${path}</p><p class="muted">${prompt}</p><div class="chips">${ns.map(para).join('')}</div></article>`).join('');
const lyrics=groups.map((parts,i)=>`<section class="lyric-group" id="l-${i+1}"><p class="meta">原文段落 ${i+1} ${link('#m-'+stages.find(s=>s[2].includes(i+1))[0],'回到本曲地圖')}</p><h2>${stages.find(s=>s[2].includes(i+1))[1]}</h2>${i===7?'<p class="note">與第3段相同的原文完整保留。這次先回想，再比較第7段的請求如何改變聆聽感受。</p>':''}${parts.map(([jp,zh,note,gs],j)=>`<article class="phrase" id="p-${i+1}-${j+1}"><span class="meta">短句 ${i+1}.${j+1}</span><h3 lang="ja">${ruby(jp)}</h3><p class="translation">${zh}</p><details><summary>語意、句構與語氣</summary><p>${note}</p><div class="chips">${gs.map(gl).join('')}</div></details></article>`).join('')}<details><summary>把本段接起來讀</summary><p class="joined-lyric" lang="ja">${parts.map(p=>ruby(p[0])).join(' ')}</p></details><h3>本段字詞</h3><div class="chips">${words.flatMap((w,j)=>w.slice(4).includes(i+1)?[link('#w-'+(j+1),ruby(w[0]))]:[]).join('')}</div><div class="chips">${i?para(i):''}${i<7?para(i+2):''}${link('#practice','回想練習')}</div></section>`).join('');
const grammarHtml=grammar.map(([id,title,form,note,jp,zh])=>`<article class="entry" id="g-${id}"><h3>${title}</h3><p class="formula">${esc(form)}</p><p>${note}</p><div class="example"><p lang="ja">${ruby(jp)}</p><p>${zh}</p></div><div class="chips">${groups.flatMap((g,i)=>g.some(p=>p[3].includes(id))?[para(i+1)]:[]).join('')}</div></article>`).join('');
const vocab=words.map(([jp,pos,meaning,note,...ns],i)=>`<article class="word" id="w-${i+1}" data-search="${esc([plain(jp),kana(jp),pos,meaning,note].join(' '))}"><h3 lang="ja">${ruby(jp)}</h3><p class="meta">${pos}</p><p><strong>${meaning}</strong>。${note}</p><div class="chips">${ns.map(para).join('')}</div></article>`).join('');
const exercises=practice.map(([q,jp,note,g,n],i)=>`<article class="exercise"><h3>${i+1}. ${q}</h3><label for="answer-${i}">先口述或試寫，再核對（此欄不儲存）</label><textarea id="answer-${i}" rows="2"></textarea><details><summary>答案與回饋</summary><p lang="ja">${ruby(jp)}</p><p>${note}</p><div class="chips">${gl(g)}${para(n)}</div></details></article>`).join('');
const html=`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><meta name="googlebot" content="noindex,nofollow"><title>ひかりもの｜AIMYON 日文學習・假設、感受與重新開始</title><meta name="description" content="ひかりもの完整使用者原文、假名、逐句中文、語法、詞彙與回想練習。"><link rel="stylesheet" href="../ring-ding/style.css"><link rel="stylesheet" href="../rhythm64/style.css"><link rel="stylesheet" href="style.css"><script src="../ring-ding/app.js" defer></script></head><body><a class="skip" href="#lyrics">跳至逐句教材</a><header id="top"><a href="../songs/">← 歌曲學習帳</a> · <a href="../learning-map/?song=hikarimono#routes">跨曲學習地圖</a><p class="eyebrow">AIMYON NOTEBOOK · 10</p><h1 lang="ja">ひかりもの</h1><p class="lead">想留住，也想放下。帶著仍然會受傷的心，重新開始。</p><p class="meta">作詞・作曲：あいみょん｜收錄於《瞬間的シックスセンス》</p><nav aria-label="教材導覽"><a href="#map">六站地圖</a><a href="#lyrics">8 段・${count} 短句</a><a href="#grammar">${grammar.length} 組句構</a><a href="#words">${words.length} 個字詞</a><a href="#compare">對照閱讀</a><a href="#practice">12 題回想</a><a href="#connections">跨曲連結</a></nav><div class="controls" hidden><button type="button" id="reading-toggle" aria-pressed="false">隱藏假名</button><button type="button" id="translation-toggle" aria-pressed="false">隱藏逐句中文</button></div></header><main>
<section class="start"><h2>今天先抓一個差異</h2><p>先讀<a href="#l-3">第3段</a>與<a href="#l-7">第7段</a>：宣告不哭，與此刻快哭，為什麼可以並存？先提出你的解釋，再看<a href="#compare">對照閱讀</a>。</p><p>每次選一段，用「讀音 → 詞義 → 句構 → 語氣 → 跨曲比較 → 自己造句」來回練習。不需要一次背完全部。</p></section>
<section id="map"><h2>六站思緒記憶地圖</h2><p>連線是閱讀引導，不宣稱同一意象只有一種解答。文法依句構辨識；人物與情緒的解讀另行說明。</p><div class="map">${map}</div></section>
<section id="lyrics"><h2>8 段原文，${count} 個閱讀短句</h2><p class="note">依你提供的原文完整編排，包含重複副歌；只增加斷句、漢字假名與教材譯文。短句數是手機閱讀編排，不是官方行數；假名不表示高低音調。</p>${lyrics}</section>
<section id="grammar"><h2>${grammar.length} 組句構與語氣</h2><p>以下例句是教學自編句。先還原活用，再回原句確認主體、時間與語氣。</p>${grammarHtml}</section>
<section id="words"><h2>${words.length} 個字詞與片語</h2><div class="search" hidden><label for="word-search">搜尋日文、假名、中文</label><input id="word-search" type="search" placeholder="例如：なぐさめる、安慰、防波堤"><p id="word-count" role="status"></p><button id="clear-search" type="button">顯示全部字詞</button></div><div class="vocab">${vocab}</div></section>
<section id="compare"><h2>三組對照，讀懂情緒的層次</h2><article class="entry"><h3>決心 ≠ 當下感受</h3><p lang="ja">${ruby('泣[な]かないぞ。／泣[な]きそうだな。')}</p><p>前者是自我宣告，後者是當下樣態。決心與難過可以並存；教材不把「不哭」訂為成熟或學習成功的標準。</p></article><article class="entry"><h3>回望另一種可能 ≠ 條件已經成立</h3><p lang="ja">${ruby('触[ふ]れていたなら → 優[やさ]しくなれたかな')}</p><p>なら與可能過去形連讀，呈現假設和自問；不是已確定的因果規律，更不保證有人接觸就必然改變性格。</p><a href="#g-nara">假設拆解 →</a></article><article class="entry"><h3>堤防、流來、退去：先找動作，再談比喻</h3><p>思緒是「越過、流來」的主體；魂是「被吸入」的對象。可以把堤防讀作壓住情緒的界線，但這是有文本依據的解讀，不是對心理疾病的判斷。</p><a href="#l-4">回到完整段落 →</a></article><article class="entry"><h3>請求安慰，也練習表達界線</h3><p>「更體貼的話」是說話者的需要；可練習清楚提出請求，而不要求同學分享私人的受傷經歷。</p><p lang="ja">${ruby('今[いま]は、少[すこ]し話[はなし]を聞[き]いてもらえる？')}</p><p>現在可以聽我說一下嗎？（教學改寫）</p></article></section>
<section id="practice"><h2>12 題回想與轉用</h2><p>先收起解說再回答；核對後只修正一個重點，再換生活情境造句。想保存概念進度可使用<a href="../learning-map/?song=hikarimono#routes">跨曲地圖</a>。</p>${exercises}<article class="entry"><h3>一週安排與教學帶讀</h3><ol><li>今天：第1–3段，圈願望和假設；先答第2–4題。</li><li>隔天：不看中文回想兩句，再讀第4段找主體。</li><li>第3天：第5–6段，區分成熟的疑問、不甘與決心。</li><li>第5天：第7段，練ずに、樣態そう與請求。</li><li>第7天：第8段，重讀相同副歌，說明前文如何改變你的理解。</li></ol><p>間隔可依表現調整，不是唯一最佳時程。帶讀可用20分鐘：3分鐘回想、5分鐘示範拆句、5分鐘兩人比較、7分鐘回饋與改寫。情緒題可用虛構人物，不要求自我揭露。</p></article></section>
<section id="connections"><h2>接入跨歌曲的理解</h2><div class="map">
<article class="map-card"><h3>一路至今與湧現</h3><p><a href="../rhythm64/#g-tekita">リズム64：てきた</a> → 本曲<a href="#g-tekita">受傷的歷程</a>；再比較<a href="../rhythm64/#g-tekuru">てくる的浮現</a>。</p><a href="../learning-map/#te-kita">到能力地圖記錄自評 →</a></article>
<article class="map-card"><h3>如果與願望</h3><p><a href="../miniskirt-highlight/#g-wish">だったらいいのに</a>與本曲<a href="#g-nara">なら＋なれたかな</a>都保留未確認的可能；不可當作既成事實。</p></article>
<article class="map-card"><h3>不做與即使不</h3><p>本曲<a href="#g-zuni">知らずに</a>是沒有知道／不知情；<a href="../ai-no-hana/#g-zutomo">晴れずとも</a>是即使不放晴。不要只看到ず就翻成一樣。</p><a href="../learning-map/#zuni">否定連接地圖 →</a></article>
<article class="map-card"><h3>樣態與可能</h3><p>本曲<a href="#g-sou">泣きそう</a>與<a href="../miniskirt-highlight/#g-sou">なれそう</a>都可談預期；後者還包含可能形，與傳聞そうだ不同。</p><a href="../learning-map/#sou-evidence">樣態地圖 →</a></article>
<article class="map-card"><h3>關心的說法</h3><p>與<a href="../ring-ding/#tone">RING DING：語氣轉換</a>對照：說出需要與強硬要求有何不同？</p></article>
<article class="map-card"><h3>景物與生活的連結</h3><p><a href="../ai-no-hana/#g-metaphor">愛の花：眼淚與種子</a>、<a href="../3636/#map">3636：容器與心</a>、<a href="../marigold/">マリーゴールド：景色與回憶</a>提供意象對讀；另以<a href="../idontlikemornings/">朝が嫌い</a>比較日常感受、<a href="../KimiWaRokkuWoKikanai/">君はロックを聴かない</a>比較靠近、<a href="../ichi-ni-tsuite/#g-teiku">いちについて</a>比較往後活下去。</p></article></div></section>
<section id="sources"><h2>作品與學習依據</h2><ul><li><a href="https://www.aimyong.net/discography/detail/14/">AIMYON 官方：專輯曲目</a>，核對作品名稱與收錄專輯。</li><li><a href="https://www.joysound.com/web/search/song/732069">JOYSOUND：詞曲與歌詞核對入口</a>。教材逐句內容以使用者提供文字為準，不另補歌詞。</li><li><a href="https://www.edresearch.edu.au/guides-resources/practice-guides/spacing-and-retrieval-practice-guide-full-publication">AERO：間隔與提取練習指引</a>。支持先回想、核對及分散重訪；不等於本教材或配色已經過成效驗證。</li></ul><p class="muted">非官方個人學習教材；中文與教學說明為本教材編寫。核對日期：2026-09-09。noindex 請求搜尋引擎不收錄，但不是登入保護。無固定底部列；無 JavaScript 仍可閱讀正文。</p></section></main><footer><a href="#top">回頁首</a> · <a href="../songs/">歌曲目錄</a> · <a href="../learning-map/">能力地圖</a></footer></body></html>`;
const ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(m=>m[1]);if(ids.length!==new Set(ids).size)throw Error('Duplicate IDs');
for(const [,id] of html.matchAll(/href="#([^"]+)"/g))if(!ids.includes(id))throw Error('Missing ID '+id);
writeFileSync(new URL('index.html',import.meta.url),html);
console.log(`Built hikarimono: ${source.length} paragraphs, ${count} phrases, ${grammar.length} grammar, ${words.length} words, ${practice.length} exercises; exact supplied text and lyric readings verified.`);
