import { readFileSync, writeFileSync } from 'node:fs';
import { source, groups, grammar, words, stages, practice } from './content.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const plain=s=>s.replace(/\[[^\]]+\]/g,'');
const ruby=s=>esc(s).replace(/([\p{Script=Han}々0-9]+)\[([^\]]+)\]/gu,'<ruby>$1<rp>（</rp><rt>$2</rt><rp>）</rp></ruby>');
const compact=s=>plain(s).replace(/\s/g,'');
const a=(href,label)=>`<a href="${esc(href)}">${label}</a>`;
const para=n=>a('#l-'+n,`第 ${n} 段`);
const gLink=id=>{const g=grammar.find(g=>g[0]===id);if(!g)throw Error('Unknown grammar '+id);return a('#g-'+id,g[1]);};
const count=groups.reduce((sum,g)=>sum+g.length,0);
if(source.length!==9||groups.length!==9)throw Error('Expected 9 source paragraphs');
groups.forEach((g,i)=>{
 // The single editorial correction is visible to readers and retained in source.
 const expected=i===7?source[i].replace('合伴','合鍵'):source[i];
 if(compact(g.map(p=>p[0]).join(''))!==compact(expected))throw Error('Unexpected source change '+(i+1));
 for(const [jp] of g)if(/[\p{Script=Han}々]/u.test(jp.replace(/[\p{Script=Han}々0-9]+\[[^\]]+\]/gu,'')))throw Error('Missing reading '+jp);
});
const mapHtml=stages.map(([id,title,ns,path,prompt],i)=>`<article class="map-card" id="m-${id}"><span class="number">${String(i+1).padStart(2,'0')}</span><h3>${title}</h3><p>${path}</p><p class="muted">${prompt}</p><div class="chips">${ns.map(para).join('')}</div></article>`).join('\n');
const groupHtml=groups.map((parts,i)=>{
 const n=i+1,stage=stages.find(s=>s[2].includes(n));
 const wordLinks=words.flatMap((w,j)=>w[5].includes(n)?[a('#w-'+(j+1),ruby(w[0]))]:[]);
 return `<section class="lyric-group" id="l-${n}"><div class="meta"><span>原文段落 ${String(n).padStart(2,'0')}</span>${a('#m-'+stage[0],'回到地圖')}</div><h2>${stage[1]}</h2>${n===9?`<p class="note">重複${para(4)}：先回想誰把什麼關起來，再重新閱讀。</p>`:''}${parts.map(([jp,zh,note,gs],j)=>`<article class="phrase" id="p-${n}-${j+1}"><span class="meta">短句 ${n}.${j+1}</span><h3 lang="ja">${ruby(jp)}</h3><p class="translation">${zh}</p><details><summary>語意、句構與語氣</summary><p>${note}</p><div class="chips">${gs.map(gLink).join('')}</div></details></article>`).join('\n')}<details class="joined"><summary>把本段接起來讀</summary><p class="joined-lyric" lang="ja">${parts.map(p=>ruby(p[0])).join(' ')}</p><p class="translation">${parts.map(p=>p[1]).join('')}</p></details><h3>本段字詞</h3><div class="chips" lang="ja">${wordLinks.join('')}</div><div class="chips">${n>1?para(n-1):''}${n<9?para(n+1):''}${a('#practice','回想練習')}</div></section>`;
}).join('\n');
const grammarHtml=grammar.map(([id,title,form,note,jp,zh],i)=>`<article class="entry" id="g-${id}"><span class="meta">句構 ${i+1}</span><h3>${title}</h3><p class="formula">${esc(form)}</p><p>${note}</p><div class="example"><p lang="ja">${ruby(jp)}</p><p>${zh}</p></div><div class="chips">${groups.flatMap((g,j)=>g.some(p=>p[3].includes(id))?[para(j+1)]:[]).join('')}</div></article>`).join('\n');
const wordHtml=words.map(([jp,reading,pos,meaning,note,ns],i)=>`<article class="word" id="w-${i+1}" data-search="${esc([plain(jp),reading,pos,meaning,note].join(' '))}"><h3 lang="ja">${ruby(jp)}</h3><p class="meta">${reading} · ${pos}</p><p><strong>${meaning}</strong>。${note}</p><div class="chips">${ns.map(para).join('')}</div></article>`).join('\n');
const practiceHtml=practice.map(([q,jp,note,g,n],i)=>`<article class="exercise"><h3>${i+1}. ${q}</h3><label for="answer-${i}">先自己回答，再核對</label><textarea id="answer-${i}" rows="2" placeholder="可以口述或在這裡試寫；此欄不會儲存。"></textarea><details><summary>展開答案與回饋</summary><div class="example"><p lang="ja">${ruby(jp)}</p><p>${note}</p></div><div class="chips">${gLink(g)}${para(n)}</div><p class="muted">答錯時回看一個對應短句，稍後再試。能解釋後，換一個名詞或情境造句。</p></details></article>`).join('\n');
const html=`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="robots" content="noindex, nofollow, noarchive, nosnippet"><meta name="googlebot" content="noindex, nofollow, nosnippet"><title>3636｜愛繆日文教材・日常自問與箱格記憶地圖</title><meta name="description" content="3636完整假名、中文解析、語法、字詞與回想練習，從日常自問讀懂宅配箱和心扉的意象。"><link rel="stylesheet" href="../ring-ding/style.css"><link rel="stylesheet" href="../rhythm64/style.css"><link rel="stylesheet" href="style.css"><script src="../ring-ding/app.js" defer></script></head><body><a class="skip" href="#lyrics">跳到逐段教材</a><header id="top"><a href="../songs/">← 歌曲學習帳</a><p class="eyebrow">AIMYON NOTEBOOK · 08</p><h1 lang="ja">${ruby('3636[さんろくさんろく]')}</h1><p class="lead">打不開的箱子裡，放著哪些未說完的日常？</p><p class="meta">作詞・作曲：あいみょん</p><nav aria-label="教材目錄"><a href="#lyrics">9 段拆讀</a><a href="#map">思緒地圖</a><a href="#grammar">${grammar.length} 組句構</a><a href="#words">${words.length} 個字詞</a><a href="#compare">箱格對照</a><a href="#practice">回想練習</a><a href="#connections">跨曲連結</a></nav><div class="controls" hidden><button type="button" id="reading-toggle" aria-pressed="false">隱藏假名</button><button type="button" id="translation-toggle" aria-pressed="false">隱藏逐句中文</button></div></header>
<main><section class="start"><h2>先分清楚：猜測，還是明說的事？</h2><p>今天從${para(1)}開始，找出の？與のかな，再用自己的話說「敘述者在猜什麼」。接著到${para(4)}，找一個明確的主語。先回答、再看解說，每次沿一條連結學即可。</p><a href="#l-1" class="primary">開始第一段</a></section>
<aside class="note" id="editorial"><strong>字詞校對</strong><p>您提供的第8段寫「合伴」。核對${a('https://www.joysound.com/web/search/song/932333','JOYSOUND 歌詞資料')}，此處為<span lang="ja">${ruby('合鍵[あいかぎ]')}</span>，意思是備用鑰匙。教材採校正字，原字記錄於此；其餘字詞依提供原文保留。不要把「合伴」當成合鍵的另一種寫法。</p></aside>
<section id="map"><h2>七站思緒記憶地圖</h2><p>讀音 → 詞義 → 句構 → 語氣 → 意象 → 自己的句子。地圖可從任何一站進入，但每次只選一個問題追下去。</p><div class="map">${mapHtml}</div></section>
<section id="lyrics"><h2>9 段原文，${count} 個閱讀短句</h2><p class="note">完整保留重複副歌，漢字及數量詞標假名，中文為本教材重譯。${count}個短句是手機閱讀的編排，不是官方行數。除上方標明的合鍵校正，內容逐段比對提供原文；讀音未標高低音調。</p>${groupHtml}</section>
<section id="grammar"><h2>${grammar.length} 組句構與用法</h2><p>把歌詞的省略和日常標準搭配放在一起看。先能指出原句依據，再用下面的自創例句練習。</p>${grammarHtml}</section>
<section id="words"><h2>${words.length} 個字詞與片語</h2><div class="search" hidden><label for="word-search">搜尋日文、假名或中文</label><input id="word-search" type="search" placeholder="例如：合鍵、あいづち、密碼" autocomplete="off"><p role="status" id="word-count" class="meta"></p><button type="button" id="clear-search">顯示全部字詞</button></div><div class="vocab">${wordHtml}</div></section>
<section id="compare"><h2>同樣打不開，封存的內容卻改變了</h2><div class="table-wrap"><table><caption>兩次副歌的明確文字對照</caption><thead><tr><th scope="col">線索</th><th scope="col">第4、9段</th><th scope="col">第7段</th></tr></thead><tbody><tr><th scope="row">箱格</th><td>5號</td><td>2號</td></tr><tr><th scope="row">封存物</th><td>兩人的回憶</td><td>你的身影</td></tr><tr><th scope="row">關閉者</th><td lang="ja">私[わたし]が</td><td lang="ja">あなたが</td></tr><tr><th scope="row">關閉對象</th><td lang="ja">その扉[とびら]</td><td lang="ja">その心[こころ]</td></tr><tr><th scope="row">共同狀態</th><td colspan="2" lang="ja">簡単[かんたん]には開[あ]かない</td></tr></tbody></table></div><div class="chips">${para(4)}${para(7)}${para(9)}</div>
<article class="entry"><h3>箱格號碼不等於密碼</h3><p>5番、2番明指宅配箱位置；暗証番号是另一項資訊。歌詞沒有明說實際密碼就是歌名3636，本教材也不把這種聯想寫成定論。先能辨別詞的功能，再提出有條件的意象推想。</p></article>
<article class="entry"><h3>不是所有「我覺得」都有對方的確認</h3><p>反覆的の？、のかな是敘述者尋找理由；私が／あなたが則在副歌明確說出行動者。閱讀時可把句子分為「文本明說」與「敘述者猜測」，再把自己的解讀放在第三欄，避免三者混為一談。</p><div class="example"><p lang="ja">最近[さいきん]、どう感[かん]じてる？ 私[わたし]は少[すこ]し寂[さび]しい。</p><p>最近你的感受如何？我有一點寂寞。</p></div><p>這是自創溝通例句：問對方的感受，也說明自己的感受，不先替對方指定厭倦的原因。</p></article>
<article class="entry"><h3>三種アレンジ，一個反覆的疑問</h3><ul><li>${para(1)}：日子裡缺少新意。</li><li>${para(2)}：頭髮沒有做造型。</li><li>${para(5)}：料理沒有變化。</li></ul><p>相同借詞因搭配名詞改變意思。回想時先說出搭配，再說中文，避免只記「アレンジ＝改編」。</p></article>
<article class="entry"><h3>從共同生活，退到裝過生活的箱子</h3><p>第8段的共同語、備用鑰匙、應答，分別可連到默契、生活空間和對話互動。這是教材的關係整理；文字明說的是它們都消失了。房間成了裝過戀情的箱子，正好讓ていた和なった的時間差變得可見。</p><div class="chips">${para(8)}${gLink('time')}</div></article></section>
<section id="practice"><h2>10 題回想與轉用</h2><p>先回答再揭示，每次挑兩題。答對後換一個名詞或情境造句；只認得旋律和答案還不等於能自己使用。</p>${practiceHtml}<article class="entry"><h3>一週輕量安排</h3><ol><li>今天：第1–2段，找提問和猜測，練兩個縮約。</li><li>明天：先回想昨天，再讀第3–4段，還原後置受詞，對比開く和開ける。</li><li>第3天：第5–6段，比較三種アレンジ，練てみる和らしい。</li><li>第5天：第7–8段，遮住對照表，自己說出主語、封存物和時間方向。</li><li>第7天：第9段，回想副歌後到另一首歌找同一語法，完成5題。</li></ol><p>間隔依回想表現調整；常錯的題提早再看，已能解釋及造句的題延後。這不是固定的最佳記憶天數。</p></article>
<article class="entry"><h3>20分鐘教學引導</h3><p>3分鐘：讓學習者標出第1段的問號。5分鐘：教師示範區分句構事實與角色猜測。5分鐘：由學習者比較兩個箱格，說出私が與あなたが。最後7分鐘：遮住解說做一題，改寫一句日常問候，再用一個字詞支持自己的意象解讀。</p><p>回饋分為讀音、助詞、解讀依據三項，一次先修正一項。討論關係只需使用歌詞或虛構情境，不要求分享私人經歷，也不把角色的自責當成學習者該接受的教訓。</p></article></section>
<section id="connections"><h2>跨歌曲，讓新句接回舊記憶</h2><article class="entry"><h3>推測和疑問</h3><p>本曲${gLink('question')}的のかな，接到${a('../rhythm64/#g-darou','〈リズム64〉なんだろうか')}：兩者都保留不確定，但一首在猜對方感受，另一首自問活法與幸福。</p></article><article class="entry"><h3>試著查、試著摸</h3><p>本曲${gLink('try')}與${a('../rhythm64/#g-try','〈リズム64〉てみる')}都表示嘗試。換成自創句：<span lang="ja">新[あたら]しい料理[りょうり]を作[つく]ってみる。</span>試著做一道新菜。</p></article><article class="entry"><h3>害怕厭倦，與直率關心</h3><p>接到${a('../ring-ding/#tone','〈RING DING〉語氣轉換')}，比較質問、命令與給對方空間的邀請。再到${a('../KimiWaRokkuWoKikanai/','〈君はロックを聴かない〉')}觀察如何嘗試靠近另一個人。</p></article><article class="entry"><h3>房間、回憶與意象</h3><p>本曲的箱子，可和${a('../ai-no-hana/#g-metaphor','〈愛の花〉意象與比喻')}、${a('../marigold/','〈マリーゴールド〉回憶畫面')}一起比較。${a('../idontlikemornings/','〈朝が嫌い〉')}也有房間與等待，${a('../ichi-ni-tsuite/#g-omission','〈いちについて〉省略')}則可練習把沒寫出的主語保留為推測。</p></article><a href="../songs/">返回八首歌曲目錄 →</a></section>
<section id="sources"><h2>校對來源與學習依據</h2><ul><li>${a('https://www.aimyong.net/news/detail/2101','AIMYON 官方〈3636〉音樂錄影帶')}：作品與聆聽入口。每次挑一小段先辨音，再看假名。</li><li>${a('https://www.joysound.com/web/search/song/932333','JOYSOUND〈3636〉歌詞與詞曲資訊')}：核對合鍵和作品資料；教材主文仍以使用者提供內容為底本。</li><li>${a('https://utaten.com/lyric/ma22072910/','讀音核對入口')}：協助查合鍵、相槌和開かない等讀法。</li><li>${a('https://www.nature.com/articles/s44159-022-00089-1','Carpenter、Pan、Butler（2022）：間隔與提取練習回顧')}：支援分散回想與校準理解的方向。</li><li>${a('https://www.nature.com/articles/s44271-025-00234-5','2025：線上講課插入測驗的研究')}：提供學習過程中加入回想題的研究參考，不是本歌詞教材的成效驗證。</li><li>${a('https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag','Google 搜尋索引指令說明')}：本頁設定noindex；這是請搜尋引擎不收錄，不是密碼保護。</li></ul><p class="meta">非官方個人學習整理。全向學習是讀音、詞義、句構、語氣、意象和產出的多入口編排；不宣稱配色或歌曲本身能啟動特定腦區。中文與練習為本教材編寫，字詞校對和詩意解讀各自標明。核對日期：2026-09-08。</p></section></main><footer><a href="#top">回到頁首</a> · <a href="../songs/">歌曲學習帳</a></footer></body></html>`;
const output=html.replace(/([\p{Script=Han}々0-9]+)\[([^\]]+)\]/gu,'<ruby>$1<rp>（</rp><rt>$2</rt><rp>）</rp></ruby>');
const ids=[...output.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
if(new Set(ids).size!==ids.length)throw Error('Duplicate ids');
for(const [,id] of output.matchAll(/href="#([^"]+)"/g))if(!ids.includes(id))throw Error('Missing anchor '+id);
for(const [,path,hash] of output.matchAll(/(?:href|src)="(\.\.\/[^"#]+)(?:#([^"]+))?"/g)){
 const target=readFileSync(new URL(path+(path.endsWith('/')?'index.html':''),import.meta.url),'utf8');
 if(hash&&!target.includes(`id="${hash}"`))throw Error('Missing cross-song anchor '+path+'#'+hash);
}
for(const w of words)if(!w[5].length||w[5].some(n=>n<1||n>9))throw Error('Invalid word reference');
writeFileSync(new URL('./index.html',import.meta.url),output);
console.log(`Built 3636: ${groups.length} paragraphs; ${count} reading phrases; ${grammar.length} grammar topics; ${words.length} words; ${practice.length} exercises. Source matches with one declared correction; readings, anchors and cross-song links verified.`);
